// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'array_example', kind: "module", path: './array_example.html', attributes: []},
{name: 'getopt_example', kind: "module", path: './getopt_example.html', attributes: []},
{name: 'string_example', kind: "module", path: './string_example.html', attributes: []},
];
